'use client';
import { FormEvent,useMemo,useState } from 'react';
import { Bell,BookOpen,Check,ChevronRight,FolderKanban,History,LayoutDashboard,LogOut,Network,Search,Sparkles,Upload } from 'lucide-react';
import { Avatar,AvatarFallback } from '@/components/ui/avatar'; import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupContent,SidebarGroupLabel,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger } from '@/components/ui/sidebar';
import { Login } from './login'; import { ProjectDocumentPanel,ResearchPanel } from './document-panels'; import { MyWork,ProjectsView } from './project-views'; import { AuditView,ResearchView } from './research-audit-views';
import { initialProjectDocuments,initialResearch,ProjectDocument,ResearchFile,View } from './prototype-data'; import { usePrototypeTools } from './use-prototype-tools';
export default function Home(){
 const[loggedIn,setLoggedIn]=useState(false);const[view,setView]=useState<View>('projects');const[documents,setDocuments]=useState(initialProjectDocuments);const[researchFiles,setResearchFiles]=useState(initialResearch);const[selectedDoc,setSelectedDoc]=useState<ProjectDocument|null>(null);const[selectedResearch,setSelectedResearch]=useState<ResearchFile|null>(null);const[search,setSearch]=useState('');const[researchOpen,setResearchOpen]=useState(false);const[notice,setNotice]=useState('');
 usePrototypeTools(loggedIn,documents,setDocuments,setResearchFiles,setNotice);
 const results=useMemo(()=>{const term=search.trim().toLowerCase();if(!term)return[];return[...documents.filter(d=>`${d.name} ${d.stage} ${d.responsible} ${d.reviewer} ${d.status}`.toLowerCase().includes(term)).map(d=>({id:`d-${d.id}`,title:d.name,meta:`Project X · ${d.stage} · ${d.status}`,kind:'project' as const,item:d})),...researchFiles.filter(f=>`${f.name} ${f.category} ${f.uploadedBy}`.toLowerCase().includes(term)).map(f=>({id:`r-${f.id}`,title:f.name,meta:`Research · ${f.category}`,kind:'research' as const,item:f}))].slice(0,8)},[search,documents,researchFiles]);
 if(!loggedIn)return <Login onLogin={()=>setLoggedIn(true)}/>;
 function reviewDecision(status:'Approved'|'Changes requested'){if(!selectedDoc)return;const updated={...selectedDoc,status,updated:'Just now'};setDocuments(items=>items.map(item=>item.id===updated.id?updated:item));setSelectedDoc(updated);setNotice(status==='Approved'?`${updated.name} ${updated.version} was approved.`:`Changes were requested for ${updated.name} ${updated.version}.`)}
 function addResearch(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')||'New research file.pdf');const category=String(data.get('category')||'Materials / Metals');setResearchFiles(items=>[{id:Date.now(),name,category,uploadedBy:'Ananya Rao',updated:'Just now',kind:'PDF'},...items]);setResearchOpen(false);setNotice(`${name} was added to the research library.`);event.currentTarget.reset()}
 const nav:[View,string,typeof LayoutDashboard][]=[['my-work','My work',LayoutDashboard],['projects','Projects',FolderKanban],['research','Research library',BookOpen],['audit','Activity log',History]];
 const headings:Record<View,[string,string]>={'my-work':['My work','Assignments and reviews that need attention.'],projects:['Project documentation','Required documents, responsibilities, and review status.'],research:['Research library','Browse and share company knowledge.'],audit:['Activity log','Every important action remains traceable.']};
 return <SidebarProvider style={{'--sidebar-width':'15.5rem'} as React.CSSProperties}>
  <Sidebar collapsible="icon"><SidebarHeader className="border-b border-white/10 bg-[#102d23] px-3 py-4 text-white"><div className="flex items-center gap-3 overflow-hidden px-1"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-[#c7f36b] text-[#143326]"><Network className="size-5"/></span><div className="group-data-[collapsible=icon]:hidden"><p className="font-semibold tracking-[0.18em]">VERDANT</p><p className="text-[11px] text-emerald-100/50">DOCUMENT HUB</p></div></div></SidebarHeader><SidebarContent className="bg-[#102d23] text-emerald-50"><SidebarGroup className="pt-4"><SidebarGroupLabel className="text-emerald-100/45">Workspace</SidebarGroupLabel><SidebarGroupContent><SidebarMenu className="gap-1">{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} tooltip={label} onClick={()=>setView(id)} className="h-10 text-emerald-50/70 hover:bg-white/10 hover:text-white data-active:bg-[#c7f36b] data-active:text-[#143326]"><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup><SidebarGroup className="mt-auto"><div className="mx-2 rounded-lg border border-white/10 bg-white/[0.06] p-3 group-data-[collapsible=icon]:hidden"><div className="flex items-center gap-2 text-xs text-emerald-50/75"><Sparkles className="size-3.5 text-[#c7f36b]"/>Fast search enabled</div><p className="mt-2 text-[11px] leading-4 text-emerald-100/45">Search names, types, projects, people, and status.</p></div></SidebarGroup></SidebarContent><SidebarFooter className="border-t border-white/10 bg-[#102d23] p-3 text-white"><div className="flex items-center gap-3 overflow-hidden"><Avatar className="size-8 shrink-0"><AvatarFallback className="bg-white/10 text-xs text-white">AR</AvatarFallback></Avatar><div className="min-w-0 flex-1 group-data-[collapsible=icon]:hidden"><p className="truncate text-sm font-medium">Ananya Rao</p><p className="truncate text-[11px] text-emerald-100/45">Project owner</p></div><Button onClick={()=>setLoggedIn(false)} variant="ghost" size="icon-sm" className="text-emerald-50/60 hover:bg-white/10 hover:text-white" aria-label="Sign out"><LogOut/></Button></div></SidebarFooter></Sidebar>
  <SidebarInset className="min-w-0 bg-[#f4f7f5]"><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-6"><SidebarTrigger className="md:hidden"/><div className="relative mx-auto w-full max-w-2xl"><Search className="absolute left-3 top-1/2 z-10 size-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search every document, project, person, or status…" aria-label="Search all company documents" className="h-10 border-slate-200 bg-slate-50 pl-9 pr-24 text-[15px] shadow-none focus-visible:bg-white"/><Badge variant="outline" className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 border-slate-200 bg-white text-[11px] text-slate-500">Metadata search</Badge>{search&&<div className="absolute left-0 right-0 top-12 z-50 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_18px_55px_rgba(15,23,42,0.18)]"><div className="border-b border-slate-100 px-4 py-2.5 text-xs font-medium uppercase tracking-[0.08em] text-slate-400">{results.length} results across projects and research</div>{results.length?results.map(result=><button key={result.id} onClick={()=>{if(result.kind==='project')setSelectedDoc(result.item as ProjectDocument);else setSelectedResearch(result.item as ResearchFile);setSearch('')}} className="flex w-full items-center gap-3 border-b border-slate-100 px-4 py-3 text-left last:border-0 hover:bg-emerald-50"><span className={`flex size-9 items-center justify-center rounded-lg ${result.kind==='project'?'bg-emerald-50 text-emerald-700':'bg-sky-50 text-sky-700'}`}>{result.kind==='project'?<FolderKanban className="size-4"/>:<BookOpen className="size-4"/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{result.title}</p><p className="mt-0.5 truncate text-xs text-slate-500">{result.meta}</p></div><ChevronRight className="size-4 text-slate-400"/></button>):<div className="px-4 py-8 text-center"><Search className="mx-auto size-5 text-slate-300"/><p className="mt-2 text-sm text-slate-500">No matching documents</p></div>}<div className="flex items-center gap-2 bg-slate-50 px-4 py-2 text-xs text-slate-400"><Sparkles className="size-3.5"/>Topic and full-document search is planned for a future version.</div></div>}</div><Button variant="ghost" size="icon" aria-label="Notifications" className="relative"><Bell/><span className="absolute right-1.5 top-1.5 size-2 rounded-full border-2 border-white bg-rose-500"/></Button></header>
   <main className="mx-auto w-full max-w-[1500px] px-4 py-6 md:px-7 lg:py-8">{notice&&<div role="status" className="mb-5 flex items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><span className="flex items-center gap-2"><Check className="size-4"/>{notice}</span><button onClick={()=>setNotice('')} className="font-medium underline underline-offset-4">Dismiss</button></div>}<div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">Verdant workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-[28px]">{headings[view][0]}</h1><p className="mt-1.5 text-sm text-slate-500">{headings[view][1]}</p></div>{view==='projects'&&<ProjectsView documents={documents} onOpen={setSelectedDoc}/>} {view==='my-work'&&<MyWork documents={documents} onOpen={setSelectedDoc}/>} {view==='research'&&<ResearchView files={researchFiles} onOpen={setSelectedResearch} onAdd={()=>setResearchOpen(true)}/>} {view==='audit'&&<AuditView/>}</main>
  </SidebarInset>
  <ProjectDocumentPanel document={selectedDoc} onClose={()=>setSelectedDoc(null)} onDecision={reviewDecision}/><ResearchPanel file={selectedResearch} onClose={()=>setSelectedResearch(null)}/>
  <Dialog open={researchOpen} onOpenChange={setResearchOpen}><DialogContent className="sm:max-w-lg"><form onSubmit={addResearch}><DialogHeader><DialogTitle>Upload a research file</DialogTitle><DialogDescription>Add a file to the open company knowledge library.</DialogDescription></DialogHeader><div className="grid gap-4 py-5"><div className="grid gap-2"><Label htmlFor="research-name">File name</Label><Input id="research-name" name="name" placeholder="e.g. Materials testing reference.pdf" required/></div><div className="grid gap-2"><Label>Classification</Label><Select defaultValue="Materials / Metals" name="category"><SelectTrigger className="h-10 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Materials / Metals">Materials / Metals</SelectItem><SelectItem value="Engineering / Body systems">Engineering / Body systems</SelectItem><SelectItem value="Market research / India">Market research / India</SelectItem><SelectItem value="Operations / Suppliers">Operations / Suppliers</SelectItem></SelectContent></Select></div><div className="rounded-xl border border-dashed border-emerald-300 bg-emerald-50/50 p-6 text-center"><Upload className="mx-auto size-6 text-emerald-700"/><p className="mt-2 text-sm font-medium">Original file remains on the company server</p><p className="mt-1 text-xs text-slate-500">The prototype creates a browser preview and library record.</p></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setResearchOpen(false)}>Cancel</Button><Button type="submit" className="bg-[#1b5e45] hover:bg-[#144b37]">Add to library</Button></DialogFooter></form></DialogContent></Dialog>
 </SidebarProvider>
}

