'use client';
import { CheckCircle2,ChevronRight,Download,Eye,FileText,Network,ZoomIn,ZoomOut } from 'lucide-react';
import { Avatar,AvatarFallback } from '@/components/ui/avatar'; import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { DocStatus,ProjectDocument,statusTone } from './prototype-data';
export function StatusBadge({status}:{status:DocStatus}){return <Badge variant="outline" className={`font-medium ${statusTone[status]}`}><span className="mr-1 size-1.5 rounded-full bg-current"/>{status}</Badge>}
export function Person({name,initials}:{name:string;initials:string}){return <div className="flex min-w-[135px] items-center gap-2"><Avatar className="size-7"><AvatarFallback className="bg-slate-100 text-[11px] font-semibold text-slate-600">{initials}</AvatarFallback></Avatar><span className="text-sm text-slate-700">{name}</span></div>}
export function ProjectTable({documents,onOpen}:{documents:ProjectDocument[];onOpen:(doc:ProjectDocument)=>void}){return <Table><TableHeader><TableRow className="border-slate-200 hover:bg-transparent"><TableHead className="pl-5 text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Required document</TableHead><TableHead className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Responsible</TableHead><TableHead className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Reviewer</TableHead><TableHead className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Due</TableHead><TableHead className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Status</TableHead><TableHead className="w-10"/></TableRow></TableHeader><TableBody>{documents.map(doc=><TableRow key={doc.id} tabIndex={0} role="button" onClick={()=>onOpen(doc)} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&onOpen(doc)} className="cursor-pointer border-slate-100 bg-white hover:bg-[#f5f8f6] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-emerald-700"><TableCell className="py-4 pl-5"><div className="flex min-w-[250px] items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg border border-emerald-100 bg-emerald-50 text-emerald-800"><FileText className="size-4"/></span><div><p className="font-medium text-slate-900">{doc.name}</p><p className="mt-0.5 text-xs text-slate-500">{doc.stage} · {doc.version}</p></div></div></TableCell><TableCell><Person name={doc.responsible} initials={doc.responsibleInitials}/></TableCell><TableCell><Person name={doc.reviewer} initials={doc.reviewerInitials}/></TableCell><TableCell className="text-sm text-slate-600">{doc.due}</TableCell><TableCell><StatusBadge status={doc.status}/></TableCell><TableCell><ChevronRight className="size-4 text-slate-400"/></TableCell></TableRow>)}</TableBody></Table>}
export function FilePreview({title,kind='Project document'}:{title:string;kind?:string}){return <div className="overflow-hidden rounded-xl border border-slate-200 bg-[#e8ece9]"><div className="flex items-center justify-between border-b border-slate-200 bg-white px-3 py-2"><div className="flex items-center gap-2 text-sm text-slate-600"><FileText className="size-4 text-emerald-700"/><span className="max-w-[220px] truncate">{title}</span></div><div className="flex items-center gap-1"><Button variant="ghost" size="icon-sm" aria-label="Zoom out"><ZoomOut/></Button><span className="px-1 text-xs text-slate-500">100%</span><Button variant="ghost" size="icon-sm" aria-label="Zoom in"><ZoomIn/></Button><Button variant="ghost" size="icon-sm" aria-label="Download original"><Download/></Button></div></div><div className="flex min-h-[430px] items-start justify-center overflow-auto p-7"><article className="min-h-[390px] w-[290px] bg-white p-7 shadow-[0_6px_24px_rgba(15,23,42,0.16)]"><div className="flex items-start justify-between border-b-2 border-emerald-800 pb-4"><div><p className="text-[9px] font-bold tracking-[0.15em] text-emerald-800">PROJECT X</p><h3 className="mt-2 text-sm font-bold leading-5 text-slate-900">{title.replace(/\.(pdf|xlsx)$/i,'')}</h3></div><Network className="size-5 text-emerald-700"/></div><p className="mt-5 text-[9px] font-semibold uppercase tracking-wide text-slate-500">{kind}</p><div className="mt-4 space-y-2">{[100,95,88,100,72].map((w,i)=><div key={i} className="h-1.5 rounded bg-slate-200" style={{width:`${w}%`}}/>)}</div><div className="mt-7 rounded border border-emerald-100 bg-emerald-50 p-4"><p className="text-[9px] font-semibold text-emerald-900">Document summary</p><div className="mt-3 space-y-2">{[90,100,84].map((w,i)=><div key={i} className="h-1.5 rounded bg-emerald-200" style={{width:`${w}%`}}/>)}</div></div><div className="mt-7 grid grid-cols-2 gap-3">{[0,1].map(i=><div key={i} className="h-16 rounded bg-slate-100"/>)}</div><p className="mt-8 text-center text-[8px] text-slate-400">Page 1 of 12</p></article></div></div>}
export function Endorsement({label}:{label:string}){return <Badge className="bg-[#eefad8] text-[#426417] hover:bg-[#eefad8]"><CheckCircle2/>{label}</Badge>}
