"""PostgreSQL product baseline

Revision ID: 0001_postgresql
Revises:
Create Date: 2026-09-07 01:16:53.932322
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_postgresql"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_code", sa.String(length=40), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=120), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column(
            "profile_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_index(op.f("ix_employees_employee_code"), "employees", ["employee_code"], unique=True)
    op.create_index(op.f("ix_employees_username"), "employees", ["username"], unique=True)
    op.create_index(op.f("ix_employees_department"), "employees", ["department"], unique=False)
    op.create_index(op.f("ix_employees_is_active"), "employees", ["is_active"], unique=False)
    op.create_table(
        "lifecycle_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_lifecycle_templates_name")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_employee_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_employee_id"],
            ["employees.id"],
            name=op.f("fk_audit_logs_actor_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_employee_id"), "audit_logs", ["actor_employee_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_project_id"), "audit_logs", ["project_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "lifecycle_template_stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["lifecycle_templates.id"],
            name=op.f("fk_lifecycle_template_stages_template_id_lifecycle_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_template_stages")),
        sa.UniqueConstraint(
            "template_id", "name", name=op.f("uq_lifecycle_template_stages_template_id_name")
        ),
        sa.UniqueConstraint(
            "template_id",
            "position",
            name=op.f("uq_lifecycle_template_stages_template_id_position"),
        ),
    )
    op.create_index(
        op.f("ix_lifecycle_template_stages_template_id"),
        "lifecycle_template_stages",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("lifecycle_template_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lifecycle_template_id"],
            ["lifecycle_templates.id"],
            name=op.f("fk_projects_lifecycle_template_id_lifecycle_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["employees.id"],
            name=op.f("fk_projects_owner_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "research_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_research_categories_created_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["research_categories.id"],
            name=op.f("fk_research_categories_parent_id_research_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_categories")),
        sa.UniqueConstraint(
            "parent_id", "name", name=op.f("uq_research_categories_parent_id_name")
        ),
    )
    op.create_index(
        op.f("ix_research_categories_name"), "research_categories", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_research_categories_parent_id"), "research_categories", ["parent_id"], unique=False
    )
    op.create_table(
        "document_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_document_types_created_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_document_types_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_types")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_document_types_project_id_name")),
    )
    op.create_index(op.f("ix_document_types_name"), "document_types", ["name"], unique=False)
    op.create_index(
        op.f("ix_document_types_project_id"), "document_types", ["project_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum(
                "VIEW",
                "EDIT",
                "REVIEW",
                "MANAGE",
                name="member_access_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("added_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["employees.id"],
            name=op.f("fk_project_members_added_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_project_members_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_members")),
        sa.UniqueConstraint(
            "project_id", "employee_id", name=op.f("uq_project_members_project_id_employee_id")
        ),
    )
    op.create_index(
        op.f("ix_project_members_employee_id"), "project_members", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_members_project_id"), "project_members", ["project_id"], unique=False
    )
    op.create_table(
        "project_stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("template_stage_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_stages_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_stage_id"],
            ["lifecycle_template_stages.id"],
            name=op.f("fk_project_stages_template_stage_id_lifecycle_template_stages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_stages")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_project_stages_project_id_name")),
        sa.UniqueConstraint(
            "project_id", "position", name=op.f("uq_project_stages_project_id_position")
        ),
    )
    op.create_index(
        op.f("ix_project_stages_project_id"), "project_stages", ["project_id"], unique=False
    )
    op.create_table(
        "research_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["research_categories.id"],
            name=op.f("fk_research_documents_category_id_research_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["employees.id"],
            name=op.f("fk_research_documents_uploaded_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_documents")),
    )
    op.create_index(
        op.f("ix_research_documents_category_id"),
        "research_documents",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_documents_name"), "research_documents", ["name"], unique=False
    )
    op.create_table(
        "document_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("document_type_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsible_employee_id", sa.Integer(), nullable=True),
        sa.Column("reviewer_employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "MISSING",
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                "ARCHIVED",
                name="requirement_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "responsible_employee_id IS NULL OR reviewer_employee_id IS NULL "
            "OR responsible_employee_id <> reviewer_employee_id",
            name=op.f("ck_document_requirements_different_responsible_reviewer"),
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_requirements_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_document_requirements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_employee_id"],
            ["employees.id"],
            name=op.f("fk_document_requirements_responsible_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_employee_id"],
            ["employees.id"],
            name=op.f("fk_document_requirements_reviewer_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["project_stages.id"],
            name=op.f("fk_document_requirements_stage_id_project_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_requirements")),
        sa.UniqueConstraint(
            "project_id", "title", name=op.f("uq_document_requirements_project_id_title")
        ),
    )
    op.create_index(
        op.f("ix_document_requirements_document_type_id"),
        "document_requirements",
        ["document_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirements_project_id"),
        "document_requirements",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirements_responsible_employee_id"),
        "document_requirements",
        ["responsible_employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirements_reviewer_employee_id"),
        "document_requirements",
        ["reviewer_employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirements_stage_id"),
        "document_requirements",
        ["stage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirements_status"), "document_requirements", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_document_requirements_title"), "document_requirements", ["title"], unique=False
    )
    op.create_table(
        "document_type_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_type_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_document_type_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "document_type_id <> depends_on_document_type_id",
            name=op.f("ck_document_type_dependencies_no_self_dependency"),
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_type_dependencies_depends_on_document_type_id_document_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_document_type_dependencies_document_type_id_document_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_type_dependencies")),
        sa.UniqueConstraint(
            "document_type_id",
            "depends_on_document_type_id",
            name=op.f("uq_document_type_dependencies_document_type_id_depends_on_document_type_id"),
        ),
    )
    op.create_index(
        op.f("ix_document_type_dependencies_depends_on_document_type_id"),
        "document_type_dependencies",
        ["depends_on_document_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_type_dependencies_document_type_id"),
        "document_type_dependencies",
        ["document_type_id"],
        unique=False,
    )
    op.create_table(
        "project_research_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("research_document_id", sa.Integer(), nullable=False),
        sa.Column("linked_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["linked_by_id"],
            ["employees.id"],
            name=op.f("fk_project_research_links_linked_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_research_links_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_document_id"],
            ["research_documents.id"],
            name=op.f("fk_project_research_links_research_document_id_research_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_research_links")),
        sa.UniqueConstraint(
            "project_id",
            "research_document_id",
            name=op.f("uq_project_research_links_project_id_research_document_id"),
        ),
    )
    op.create_index(
        op.f("ix_project_research_links_project_id"),
        "project_research_links",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_research_links_research_document_id"),
        "project_research_links",
        ["research_document_id"],
        unique=False,
    )
    op.create_table(
        "research_document_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("research_document_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=180), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_document_id"],
            ["research_documents.id"],
            name=op.f("fk_research_document_versions_research_document_id_research_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["employees.id"],
            name=op.f("fk_research_document_versions_uploaded_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_document_versions")),
        sa.UniqueConstraint(
            "research_document_id",
            "version_number",
            name=op.f("uq_research_document_versions_research_document_id_version_number"),
        ),
    )
    op.create_index(
        op.f("ix_research_document_versions_checksum_sha256"),
        "research_document_versions",
        ["checksum_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_document_versions_research_document_id"),
        "research_document_versions",
        ["research_document_id"],
        unique=False,
    )
    op.create_table(
        "research_endorsements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("research_document_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_research_endorsements_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_document_id"],
            ["research_documents.id"],
            name=op.f("fk_research_endorsements_research_document_id_research_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_endorsements")),
        sa.UniqueConstraint(
            "research_document_id",
            "employee_id",
            name=op.f("uq_research_endorsements_research_document_id_employee_id"),
        ),
    )
    op.create_index(
        op.f("ix_research_endorsements_employee_id"),
        "research_endorsements",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_endorsements_research_document_id"),
        "research_endorsements",
        ["research_document_id"],
        unique=False,
    )
    op.create_table(
        "document_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum(
                "VIEW",
                "EDIT",
                "REVIEW",
                "MANAGE",
                name="document_access_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("granted_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_document_permissions_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["employees.id"],
            name=op.f("fk_document_permissions_granted_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["document_requirements.id"],
            name=op.f("fk_document_permissions_requirement_id_document_requirements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_permissions")),
        sa.UniqueConstraint(
            "requirement_id",
            "employee_id",
            name=op.f("uq_document_permissions_requirement_id_employee_id"),
        ),
    )
    op.create_index(
        op.f("ix_document_permissions_employee_id"),
        "document_permissions",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_permissions_requirement_id"),
        "document_permissions",
        ["requirement_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_documents_created_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["document_requirements.id"],
            name=op.f("fk_documents_requirement_id_document_requirements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_name"), "documents", ["name"], unique=False)
    op.create_index(
        op.f("ix_documents_requirement_id"), "documents", ["requirement_id"], unique=True
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=180), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_document_versions_created_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id",
            "version_number",
            name=op.f("uq_document_versions_document_id_version_number"),
        ),
    )
    op.create_index(
        op.f("ix_document_versions_checksum_sha256"),
        "document_versions",
        ["checksum_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_table(
        "document_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_version_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "UNDER_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                name="review_decision",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_reviews_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_employee_id"],
            ["employees.id"],
            name=op.f("fk_document_reviews_reviewer_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_reviews")),
        sa.UniqueConstraint(
            "document_version_id", name=op.f("uq_document_reviews_document_version_id")
        ),
    )
    op.create_index(
        op.f("ix_document_reviews_document_version_id"),
        "document_reviews",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_reviews_reviewer_employee_id"),
        "document_reviews",
        ["reviewer_employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_reviews_reviewer_employee_id"), table_name="document_reviews")
    op.drop_index(op.f("ix_document_reviews_document_version_id"), table_name="document_reviews")
    op.drop_table("document_reviews")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_checksum_sha256"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_requirement_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_name"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_document_permissions_requirement_id"), table_name="document_permissions")
    op.drop_index(op.f("ix_document_permissions_employee_id"), table_name="document_permissions")
    op.drop_table("document_permissions")
    op.drop_index(
        op.f("ix_research_endorsements_research_document_id"), table_name="research_endorsements"
    )
    op.drop_index(op.f("ix_research_endorsements_employee_id"), table_name="research_endorsements")
    op.drop_table("research_endorsements")
    op.drop_index(
        op.f("ix_research_document_versions_research_document_id"),
        table_name="research_document_versions",
    )
    op.drop_index(
        op.f("ix_research_document_versions_checksum_sha256"),
        table_name="research_document_versions",
    )
    op.drop_table("research_document_versions")
    op.drop_index(
        op.f("ix_project_research_links_research_document_id"), table_name="project_research_links"
    )
    op.drop_index(op.f("ix_project_research_links_project_id"), table_name="project_research_links")
    op.drop_table("project_research_links")
    op.drop_index(
        op.f("ix_document_type_dependencies_document_type_id"),
        table_name="document_type_dependencies",
    )
    op.drop_index(
        op.f("ix_document_type_dependencies_depends_on_document_type_id"),
        table_name="document_type_dependencies",
    )
    op.drop_table("document_type_dependencies")
    op.drop_index(op.f("ix_document_requirements_title"), table_name="document_requirements")
    op.drop_index(op.f("ix_document_requirements_status"), table_name="document_requirements")
    op.drop_index(op.f("ix_document_requirements_stage_id"), table_name="document_requirements")
    op.drop_index(
        op.f("ix_document_requirements_reviewer_employee_id"), table_name="document_requirements"
    )
    op.drop_index(
        op.f("ix_document_requirements_responsible_employee_id"), table_name="document_requirements"
    )
    op.drop_index(op.f("ix_document_requirements_project_id"), table_name="document_requirements")
    op.drop_index(
        op.f("ix_document_requirements_document_type_id"), table_name="document_requirements"
    )
    op.drop_table("document_requirements")
    op.drop_index(op.f("ix_research_documents_name"), table_name="research_documents")
    op.drop_index(op.f("ix_research_documents_category_id"), table_name="research_documents")
    op.drop_table("research_documents")
    op.drop_index(op.f("ix_project_stages_project_id"), table_name="project_stages")
    op.drop_table("project_stages")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_employee_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_document_types_project_id"), table_name="document_types")
    op.drop_index(op.f("ix_document_types_name"), table_name="document_types")
    op.drop_table("document_types")
    op.drop_index(op.f("ix_research_categories_parent_id"), table_name="research_categories")
    op.drop_index(op.f("ix_research_categories_name"), table_name="research_categories")
    op.drop_table("research_categories")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        op.f("ix_lifecycle_template_stages_template_id"), table_name="lifecycle_template_stages"
    )
    op.drop_table("lifecycle_template_stages")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_project_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_employee_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("lifecycle_templates")
    op.drop_index(op.f("ix_employees_is_active"), table_name="employees")
    op.drop_index(op.f("ix_employees_department"), table_name="employees")
    op.drop_index(op.f("ix_employees_username"), table_name="employees")
    op.drop_index(op.f("ix_employees_employee_code"), table_name="employees")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
